{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/liveview-native-core.LiveViewNativeCore\/documentation\/LiveViewNativeCore","doc:\/\/liveview-native-core.LiveViewNativeCore\/documentation\/LiveViewNativeCore\/CastError"]]},"kind":"symbol","identifier":{"url":"doc:\/\/liveview-native-core.LiveViewNativeCore\/documentation\/LiveViewNativeCore\/CastError\/SocketShutdown","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/liveviewnativecore\/casterror\/socketshutdown"]}],"metadata":{"role":"symbol","symbolKind":"case","externalID":"s:18LiveViewNativeCore9CastErrorO14SocketShutdownyA2CmF","title":"CastError.SocketShutdown","modules":[{"name":"LiveViewNativeCore"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SocketShutdown","kind":"identifier"}],"roleHeading":"Case"},"abstract":[{"text":"The async task for the [Socket] was already joined by another call, so the [Result] or panic","type":"text"},{"text":" ","type":"text"},{"text":"from the async task can’t be reported here.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocketShutdown"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://liveview-native-core.LiveViewNativeCore/documentation/LiveViewNativeCore/CastError":{"url":"\/documentation\/liveviewnativecore\/casterror","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CastError"}],"type":"topic","identifier":"doc:\/\/liveview-native-core.LiveViewNativeCore\/documentation\/LiveViewNativeCore\/CastError","abstract":[{"type":"text","text":"Errors when calling [Channel::cast]."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CastError"}],"kind":"symbol","title":"CastError"},"doc://liveview-native-core.LiveViewNativeCore/documentation/LiveViewNativeCore":{"role":"collection","title":"LiveViewNativeCore","url":"\/documentation\/liveviewnativecore","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/liveview-native-core.LiveViewNativeCore\/documentation\/LiveViewNativeCore"},"doc://liveview-native-core.LiveViewNativeCore/documentation/LiveViewNativeCore/CastError/SocketShutdown":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SocketShutdown"}],"type":"topic","title":"CastError.SocketShutdown","url":"\/documentation\/liveviewnativecore\/casterror\/socketshutdown","identifier":"doc:\/\/liveview-native-core.LiveViewNativeCore\/documentation\/LiveViewNativeCore\/CastError\/SocketShutdown","kind":"symbol","abstract":[{"type":"text","text":"The async task for the [Socket] was already joined by another call, so the [Result] or panic"},{"type":"text","text":" "},{"type":"text","text":"from the async task can’t be reported here."}]}}}